[logger]
level = "DEBUG"
out_paths = ["stdout"]
err_paths = ["stderr"]

[app.http_server]
host = "localhost"
port = "5000"
read_timeout = "200ms"
write_timeout = "200ms"
read_header_timeout = "200ms"

[app.grpc_server]
host = "localhost"
port = "5080"

[app.database]
storage = "1sql"
driver = "postgres"
host = "localhost"
port = "5532"
db = "calendar"
user = "calendar"
password = "developer"
ssl = "disable"
