[logger]
level = "DEBUG"
out_paths = ["stdout"]
err_paths = ["stderr"]

[consumer]
host = "localhost"
port = "5672"
protocol = "amqp"
username = "guest"
password = "guest"
subscription = "calendar"
consumer_name = "notifications"