[logger]
level = "DEBUG"
out_paths = ["stdout"]
err_paths = ["stderr"]

[mq]
host = "localhost"
port = "5672"
protocol = "amqp"
username = "guest"
password = "guest"
subscription = "notifications"
consumer_name = "calendar"