version: '3.7'
services:
#===============STORAGE==============#
  calendar_postgres:
    image: postgres:14
    hostname: control_camunda_postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB:  ${DB_DATABASE}
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      calendar:
#====================================#

#===========MESSAGE QUEUE============#
  calendar_mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5
    restart: on-failure
    networks:
      calendar:
#====================================#
#====================================#
  migrator:
    environment:
        GOOSE_DRIVER: "postgres"
        GOOSE_DBSTRING: ${DB_USERNAME}:${DB_PASSWORD}@calendar_postgres:5432/${DB_DATABASE}?sslmode=disable
    depends_on:
        calendar_postgres:
          condition: service_healthy

  calendar:
    environment:
      APP_DATABASE_PASSWORD: ${DB_PASSWORD}
      APP_DATABASE_HOST: calendar_postgres
    depends_on:
      calendar_postgres:
        condition: service_healthy

  sender:
    depends_on:
      calendar_mq:
        condition: service_healthy
  
  scheduler:
    environment:
      APP_DATABASE_PASSWORD: ${DB_PASSWORD}
      APP_DATABASE_HOST: calendar_postgres
    depends_on:
      calendar_postgres:
        condition: service_healthy
      calendar_mq:
        condition: service_healthy

#====================================#
networks:
  calendar:
    driver: bridge

volumes:
  postgres_data: