version: '3.7'
services:
#===============STORAGE==============#
  calendar_postgres:
    image: postgres:14
    hostname: control_camunda_postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB:  ${DB_DATABASE}
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      calendar:
#====================================#

networks:
  calendar:
    driver: bridge

volumes:
  postgres_data: