// Code generated by protoc-gen-go. DO NOT EDIT.
// source: EventService.proto

package v1grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Date,proto3" json:"Date,omitempty"`
	EndDate              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	Desc                 string               `protobuf:"bytes,5,opt,name=Desc,proto3" json:"Desc,omitempty"`
	UserID               string               `protobuf:"bytes,6,opt,name=UserID,proto3" json:"UserID,omitempty"`
	RemindDate           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=RemindDate,proto3" json:"RemindDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Event) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *Event) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Event) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Event) GetRemindDate() *timestamp.Timestamp {
	if m != nil {
		return m.RemindDate
	}
	return nil
}

type Response struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type EventID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventID) Reset()         { *m = EventID{} }
func (m *EventID) String() string { return proto.CompactTextString(m) }
func (*EventID) ProtoMessage()    {}
func (*EventID) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{2}
}

func (m *EventID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventID.Unmarshal(m, b)
}
func (m *EventID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventID.Marshal(b, m, deterministic)
}
func (m *EventID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventID.Merge(m, src)
}
func (m *EventID) XXX_Size() int {
	return xxx_messageInfo_EventID.Size(m)
}
func (m *EventID) XXX_DiscardUnknown() {
	xxx_messageInfo_EventID.DiscardUnknown(m)
}

var xxx_messageInfo_EventID proto.InternalMessageInfo

func (m *EventID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EventResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{3}
}

func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (m *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(m, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

func (m *EventResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *EventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsResponse) Reset()         { *m = EventsResponse{} }
func (m *EventsResponse) String() string { return proto.CompactTextString(m) }
func (*EventsResponse) ProtoMessage()    {}
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{4}
}

func (m *EventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsResponse.Unmarshal(m, b)
}
func (m *EventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsResponse.Marshal(b, m, deterministic)
}
func (m *EventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsResponse.Merge(m, src)
}
func (m *EventsResponse) XXX_Size() int {
	return xxx_messageInfo_EventsResponse.Size(m)
}
func (m *EventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventsResponse proto.InternalMessageInfo

func (m *EventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *EventsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type EventsRequest struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventsRequest) Reset()         { *m = EventsRequest{} }
func (m *EventsRequest) String() string { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()    {}
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{6}
}

func (m *EventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsRequest.Unmarshal(m, b)
}
func (m *EventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsRequest.Marshal(b, m, deterministic)
}
func (m *EventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsRequest.Merge(m, src)
}
func (m *EventsRequest) XXX_Size() int {
	return xxx_messageInfo_EventsRequest.Size(m)
}
func (m *EventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsRequest proto.InternalMessageInfo

func (m *EventsRequest) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "v1grpc.Event")
	proto.RegisterType((*Response)(nil), "v1grpc.Response")
	proto.RegisterType((*EventID)(nil), "v1grpc.EventID")
	proto.RegisterType((*EventResponse)(nil), "v1grpc.EventResponse")
	proto.RegisterType((*EventsResponse)(nil), "v1grpc.EventsResponse")
	proto.RegisterType((*UpdateRequest)(nil), "v1grpc.UpdateRequest")
	proto.RegisterType((*EventsRequest)(nil), "v1grpc.EventsRequest")
}

func init() { proto.RegisterFile("EventService.proto", fileDescriptor_18b11b0379297b15) }

var fileDescriptor_18b11b0379297b15 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0xc7, 0x95, 0x97, 0x43, 0xc7, 0x24, 0xad, 0x56, 0x50, 0x19, 0x5f, 0xa8, 0x8c, 0x90, 0x7a,
	0x61, 0x03, 0x01, 0x71, 0x80, 0x43, 0x79, 0x6c, 0x14, 0x19, 0xa9, 0x17, 0xd3, 0x0a, 0x89, 0x9b,
	0x9b, 0x0c, 0xc1, 0xc2, 0xb1, 0xcd, 0xee, 0x24, 0x12, 0x1f, 0x86, 0x4f, 0xca, 0x05, 0x79, 0x1f,
	0xa6, 0x6e, 0x68, 0x2b, 0xf5, 0xe6, 0x99, 0xf9, 0xcf, 0x6f, 0x66, 0xfe, 0x6b, 0x60, 0xb3, 0x2d,
	0x16, 0xf4, 0x19, 0xe5, 0x36, 0x5b, 0x20, 0xaf, 0x64, 0x49, 0x25, 0xf3, 0xb6, 0x2f, 0x56, 0xb2,
	0x5a, 0x84, 0x8f, 0x57, 0x65, 0xb9, 0xca, 0x71, 0xa2, 0xb3, 0x17, 0x9b, 0x6f, 0x13, 0xca, 0xd6,
	0xa8, 0x28, 0x5d, 0x57, 0x46, 0x18, 0xfd, 0xe9, 0xc0, 0x40, 0xf7, 0xb3, 0x31, 0x74, 0x63, 0x11,
	0x74, 0x8e, 0x3a, 0xc7, 0x7b, 0x49, 0x37, 0x16, 0xec, 0x01, 0x0c, 0xce, 0x32, 0xca, 0x31, 0xe8,
	0xea, 0x94, 0x09, 0x18, 0x87, 0xbe, 0x48, 0x09, 0x83, 0xde, 0x51, 0xe7, 0xd8, 0x9f, 0x86, 0xdc,
	0xf0, 0xb9, 0xe3, 0xf3, 0x33, 0xc7, 0x4f, 0xb4, 0x8e, 0xbd, 0x82, 0xe1, 0xac, 0x58, 0xea, 0x96,
	0xfe, 0xad, 0x2d, 0x4e, 0xca, 0x18, 0xf4, 0x05, 0xaa, 0x45, 0x30, 0xd0, 0xa3, 0xf5, 0x37, 0x3b,
	0x04, 0xef, 0x5c, 0xa1, 0x8c, 0x45, 0xe0, 0xe9, 0xac, 0x8d, 0xd8, 0x1b, 0x80, 0x04, 0xd7, 0x99,
	0x1d, 0x32, 0xbc, 0x75, 0xc8, 0x25, 0x75, 0x14, 0xc1, 0xbd, 0x04, 0x55, 0x55, 0x16, 0x0a, 0x6b,
	0xbe, 0xa2, 0x94, 0x36, 0xca, 0x7a, 0x60, 0xa3, 0xe8, 0x11, 0x0c, 0xb5, 0x41, 0xb1, 0xa8, 0x2d,
	0xca, 0x96, 0xce, 0xa2, 0x6c, 0x19, 0x7d, 0x82, 0x91, 0x2e, 0x35, 0x8c, 0x27, 0x30, 0xc0, 0x3a,
	0xa1, 0x35, 0xfe, 0x74, 0xc4, 0xcd, 0x33, 0x70, 0xa3, 0x32, 0xb5, 0xda, 0xd8, 0x99, 0x94, 0xa5,
	0x74, 0xc6, 0xea, 0x20, 0x3a, 0x85, 0xb1, 0x56, 0xa9, 0x06, 0xf6, 0x14, 0x3c, 0xdd, 0x50, 0x2f,
	0xd4, 0xdb, 0xa5, 0xd9, 0xe2, 0x35, 0x38, 0x01, 0xa3, 0xf3, 0x6a, 0x99, 0x12, 0x26, 0xf8, 0x73,
	0x83, 0x8a, 0xae, 0xee, 0xfe, 0x6f, 0xd5, 0xee, 0xf5, 0xab, 0x46, 0x27, 0xf6, 0x40, 0xe5, 0x28,
	0x1c, 0xfa, 0x35, 0xd4, 0xde, 0x77, 0xe3, 0xf3, 0xd7, 0xba, 0xe9, 0xef, 0x1e, 0xdc, 0xbf, 0xfc,
	0x7b, 0xb2, 0x67, 0xd0, 0x9b, 0x23, 0xb1, 0xfd, 0xd6, 0xb8, 0x58, 0x84, 0x0f, 0xdb, 0xf3, 0x9d,
	0x07, 0x1c, 0xfc, 0x8f, 0x12, 0x53, 0x42, 0xf3, 0x8f, 0xb6, 0xb7, 0x0c, 0x0f, 0x5c, 0xd8, 0xe8,
	0x5f, 0x83, 0x6f, 0xce, 0x36, 0xfa, 0x86, 0xda, 0xf2, 0xe2, 0x3f, 0x7d, 0xcf, 0xc1, 0x17, 0x98,
	0xa3, 0xeb, 0xdb, 0x59, 0x6f, 0xb7, 0xe3, 0x04, 0xc6, 0x73, 0x24, 0x91, 0x66, 0xf9, 0x2f, 0x63,
	0x11, 0x6b, 0x9f, 0xe0, 0x2c, 0x0b, 0x0f, 0xaf, 0xa6, 0x2d, 0xe0, 0x1d, 0xec, 0xcf, 0x91, 0xbe,
	0x20, 0xfe, 0xb8, 0x2b, 0xe1, 0x3d, 0x1c, 0xcc, 0x91, 0x4e, 0xcb, 0x82, 0xbe, 0xdf, 0x11, 0xf1,
	0xc1, 0xff, 0xba, 0xc7, 0x27, 0x6f, 0x4d, 0xed, 0xc2, 0xd3, 0xcf, 0xf8, 0xf2, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf8, 0x26, 0xb6, 0x7f, 0x51, 0x04, 0x00, 0x00,
}
